export const Images = {
  dark_logo: require('./app/dark_logo.png'),
  light_logo: require('./app/light_logo.png'),
  small_logo: require('./app/small_light_logo.png'),
  dark_mode: require('./app/img_dark_mode.png'),
  light_mode: require('./app/img_light_mode.png'),
  hand_phone: require('./app/img_hand_phone.png'),
  rounded: require('./app/img_rounded.png'),
  avatar: {
    male: require('./app/img_avatar_male.png'),
    female: require('./app/img_avatar_female.png'),
    facebook: require('./app/img_facebook.png'),
    gg: require('./app/img_gg.png'),
    apple: require('./app/img_apple.png'),
    tw: require('./app/img_tw.png'),
    avatar_01: require('./app/img_avatar_01.png'),
    avatar_02: require('./app/img_avatar_02.png'),
    avatar_03: require('./app/img_avatar_03.png'),
    avatar_04: require('./app/img_avatar_04.png'),
    avatar_05: require('./app/img_avatar_05.png'),
  },
  social: {
    social01: require('./social/img_social_01.png'),
    social02: require('./social/img_social_02.png'),
    social03: require('./social/img_social_03.png'),
    social04: require('./social/img_social_04.png'),
    social05: require('./social/img_social_05.png'),
    reel01: require('./social/img_reel_01.png'),
    reel02: require('./social/img_reel_02.png'),
    reel03: require('./social/img_reel_03.png'),
    cover: require('./social/img_social_cover.png'),
  },
};
